#!/system/bin/sh
#=============================================================
#Defrags database files and optimizes SQlite databases of apps
#=============================================================

mount -o remount rw /system
mount -o remount rw /

LOG_FILE=/data/07vacuum_sqlite.log

# do nothing if less than 0 days
find $LOG_FILE -type f -mtime -5 -delete;

echo "Ignore the 'database disk image is malformed' error";
echo "Ignore the 'no such collation sequence' error";

if ! test -f $LOG_FILE; then
	if [ -e $LOG_FILE ]; then
		rm $LOG_FILE;
	fi;
    	
echo "Starting Sqlite Vacuum $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE;
sleep 5;
echo "Cleaning /data partition";
sleep 5;
	for i in \
	`find /data -iname "*.db"`
	do \
		/system/xbin/sqlite3 $i 'VACUUM;';
		/system/xbin/sqlite3 $i 'REINDEX;'; 		
		echo Vacuum $i  | tee -a $LOG_FILE;
	done;
sleep 5;
echo "Cleaning /dbdata partition";
sleep 5;
	for i in \
	`find /dbdata -iname "*.db"`
	do \
		/system/xbin/sqlite3 $i 'VACUUM;';
		/system/xbin/sqlite3 $i 'REINDEX;';  
		echo Vacuum $i  | tee -a $LOG_FILE;
	done;
sleep 5;
echo "Cleaning /sdcard partition";
sleep 5;
	for i in \
	`find /sdcard -iname "*.db"`
	do \
		/system/xbin/sqlite3 $i 'VACUUM;'; 
		/system/xbin/sqlite3 $i 'REINDEX;'; 
		echo Vacuum $i  | tee -a $LOG_FILE;
	done

	echo "Sqlite Vacuum finished at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE;
fi

echo "Complete"
